ReadyGOTravel/readygotravel/readygotravel/Controllers/TopLocationsController.cs
using readygotravel.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using readygotravel.Controllers;
using System.Xml;
using System.Net;
using System.IO;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using readygotravel.Models.ViewModels;
using readygotravel.Concrete;
using readygotravel.Abstract;
using Newtonsoft.Json;

namespace readygotravel.Controllers
{
    public class TopLocationsController : Controller
    {
        //Code needed for dependency injection and DB access
        private DBContext db = new DBContext();
        private ITravelRepo repo;
        public TopLocationsController(ITravelRepo travelRepo)
        {
            repo = travelRepo;
        }

        // GET: Top US Locations
        /// <summary>
        /// This is the main function for the Top US locations view page
        /// </summary>
        /// <returns>Returns all lists, information, and users name for said view page</returns>
        public ActionResult Index()
        {
            //New person model for login, displays name if logged in, or admin if admin in the nav bar
            Person person = new Person();
            string idTemp = User.Identity.GetUserId();
            if (idTemp != null)
            {
                //Check the id of the current user if its not null
                int? id = db.People.Where(n => n.UserID.Equals(idTemp)).First().PersonID;
                //Id should never be null, guests are always -1, this is simply for error handling
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                person = db.People.Find(id);
                if (person == null)
                {
                    return HttpNotFound();
                }

                //Check if the logged in user is an Admin or not.
                if (new PeopleController(repo).IsAdminUser(User.Identity))
                {
                    ViewBag.Admin = 1;
                }
                else
                {
                    ViewBag.Admin = 0;
                }
            }
            //Create an array of the top 12 states to reference.
            string[] states = { "Wyoming","Hawaii", "Arizona", "New York", "California", "Maryland", "Massachusetts","Nevada","Illinois", "Louisiana", "Montana", "Washington"};

            //Create all arrays such as foodCost, foodItems amounts, avgHotel Ratings based on Searches, weather, geography, etc.
            decimal[] foodCostList = new decimal[12];
            string[] avgHotelList = new string[12];
            string[] foodItemsList = new string[36];
            int[] tempsList = new int[48];
            string[] weatherList = new string[48];
            List<string> climates = new List<string>();
            List<int> climateCount = new List<int>();
            decimal[] actualCrimeList = new decimal[12];
            int[] crimeCheck = new int[12];

            //climate counter and int for said tracker
            List<int> count = new List<int>();
            int z = 0;

            //For each of the 12 states, fill the foodcost list/AvgHotelRating List with only states with the specified names.
            for (int i = 0; i < 12; i++)
            {
                //Can not do a db linq query using an array, so used a work around.
                string state = states[i];

                //DB query to pull top state's foodcost data.
                foodCostList[i] = Math.Round(db.States
                    .Where(s => s.Location.Name.Contains(state))
                    .Select(f => f.FoodCost).FirstOrDefault(), 2);

                //Function and counter to pull the three fooditem names per state (Function Tested - Adrian)
                int j = i * 3;
                CreateFoodItemsList(foodItemsList, j, state);

                //Function to pull state's crimerate data (Function Tested - Adrian)
                CreateCrimeLists(actualCrimeList, crimeCheck, i, state);

                //Function to the 4 temperatures/weather per season per state (Function Tested - Adrian)
                int k = i * 4;
                CreateTempsList(tempsList, weatherList, k, state);

                //Loop to add all climates for all states, includes a counter geoCount that helps to track what climates belong to what states
                foreach (string climate in db.States.Where(s => s.Location.Name.Contains(state))
                    .SelectMany(c => c.Climates).Select(t => t.ClimateType).ToList())
                {
                    //This makes a list of all climates for all 12 states
                    climates.Add(climate);
                    //This tracks climates per state
                    climateCount.Add(i);
                    //This is a variable used for the view page to paste correct results in the foreach loop
                    count.Add(z);
                    z++;
                }

                //Setup list of Average searhed hotel star ratings.
                avgHotelList[i] = AverageSearchedHotelStarRating(states[i]);

            }

            //ViewBags have stored lists for view page.
            ViewBag.foodList = foodCostList;
            ViewBag.hotelList = avgHotelList;
            ViewBag.foodItems = foodItemsList;
            ViewBag.actualCrime = actualCrimeList;
            ViewBag.crimeCheck = crimeCheck;
            ViewBag.temps = tempsList;
            ViewBag.weather = weatherList;
            ViewBag.climates = climates;
            ViewBag.cCount = climateCount;
            ViewBag.count = count;
            ViewBag.states = states;

            //Also return person object to display name
            return View(person);
        }

        /// <summary>
        /// This will return the TopEuropeanLocations View with some information about the locations.
        /// </summary>
        /// <returns>The TopEurpeanLocations View.</returns>
        public ActionResult TopEuropeanLocations()
        {
            //New Person Model for Login, displays name if logged in, or admin if admin in the nav bar
            Person person = new Person();
            string idTemp = User.Identity.GetUserId();
            if (idTemp != null)
            {
                //Check the id of the current user if its not null
                int? id = db.People.Where(n => n.UserID.Equals(idTemp)).First().PersonID;
                //Id should never be null, guests are always -1, this is simply for error handling
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                person = db.People.Find(id);
                if (person == null)
                {
                    return HttpNotFound();
                }

                //Check if the logged in user is an Admin or not.
                if (new PeopleController(repo).IsAdminUser(User.Identity))
                {
                    ViewBag.Admin = 1;
                }
                else
                {
                    ViewBag.Admin = 0;
                }
            }
            
            //Create an array of the top 12 locations to reference.
            string[] locations = { "Paris","Florence", "Amsterdam", "London", "Barcelona", "Rome", "Reykjavik", "Edinburgh", "Prague","Galway","Nice", "Istanbul" };
            
            //Create an avgHotel Ratings array based on Searches
            string[] avgHotelList = new string[12];
            for(int i = 0; i < 12; i++)
            {
                //Setup list of Average searhed hotel star ratings.
                avgHotelList[i] = AverageSearchedHotelStarRating(locations[i]);

            }
            ViewBag.hotelList = avgHotelList;

            //Also return person object to display name
            return View(person);
        }

        //Adrian Test
        /// <summary>
        /// Function that builds food item list, 3 for each state
        /// </summary>
        /// <param name="foodItemsList">The array that holds all of the food strings</param>
        /// <param name="j">counter that grabs 3 foods per State</param>
        /// <param name="state">the current State for tracking</param>
        public void CreateFoodItemsList(string[] foodItemsList, int j, string state)
        {
            foodItemsList[j] = repo.States.ToList().Where(s => s.Location.Name.Contains(state))
                         .Select(f => f.FoodItemOne).FirstOrDefault();
            foodItemsList[j + 1] = repo.States.ToList().Where(s => s.Location.Name.Contains(state))
                     .Select(f => f.FoodItemTwo).FirstOrDefault();
            foodItemsList[j + 2] = repo.States.ToList().Where(s => s.Location.Name.Contains(state))
                     .Select(f => f.FoodItemThree).FirstOrDefault();
        }

        /// <summary>
        /// This will give you the Average Searched Hotel Star Rating of a location.
        /// </summary>
        /// <param name="locationName">The name of the location that is being referenced.</param>
        /// <returns>The average searched hotel star rating.</returns>
        public string AverageSearchedHotelStarRating(string locationName)
        {
            //Try to find results for location searches.
            string AverageValue;
            try
            {
                //Avg the list of hotel star rating results by the selected state.
                AverageValue = Convert.ToString(Math.Round(repo.Locations.ToList()
                    .Where(s => s.Name == locationName)
                    .SelectMany(a => a.Airports)
                    .SelectMany(n => n.Searches1)
                    .SelectMany(r => r.Results)
                    .Select(r => r.AvgHotelStar)
                    .Average(), 2));
                return AverageValue;
            }

ReadyGOTravel/readygotravel/readygotravel/Views/TopLocations/Display.cshtml
@model IEnumerable<readygotravel.Models.ViewModels.TopSearched>

@{
    ViewBag.Title = "Top Searched Locations";
}


<div class="content">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <h2>Top Searched Locations</h2>
            <hr />
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.EndState)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TimesSearched)
                    </th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(model => item.EndState)
                        </td>
                        <td>
                            @Html.DisplayFor(model => item.TimesSearched)
                        </td>
                    </tr>

                }
            </table>
            <!--Used this to reference how many search items are on display-->
            <input type="hidden" value=9 id="NumStates">
            <input type="hidden" value=@ViewBag.NumSearches id="TotalNumStates">

            <!--"load more" button-->
            <div class="text-center">
                <input id="AddMore" class="btn btn-default" type="submit" value="Load More" onclick="addElements()" style="visibility: visible;" />
            </div>
        </div>
        <div class="col-md-1"></div>
    </div>
</div>
@section PageScripts{
    <script type="text/javascript" src="~/Scripts/TopSearches.js"></script>
}

ReadyGOTravel/readygotravel/readygotravel/Views/TopLocations/TopEuropeanLocations.cshtml
@model  readygotravel.Models.Person
@using Microsoft.AspNet.Identity;
@using readygotravel.Models;
@using Microsoft.AspNet.Identity.EntityFramework;
@{
    ViewBag.Title = "Top European Locations";
}


<div class="image-bar3">
    <div class="content">
        @if (Request.IsAuthenticated)
        {
            int position = @User.Identity.GetUserName().IndexOf("@");
            <h2>Welcome @Html.DisplayFor(model => model.FirstName)! </h2>

        }
        else
        {
            <h2>Welcome Guest!</h2>
        }
        <div class="d-flex justify-content-center">
            <div class="row">
                <h4>We may be able to help you pick your next Dream Destination!</h4>
            </div>
        </div>
        <hr />
        <div class="d-flex justify-content-center">
            <div class="row">
                <h6>Here we Showcase the Top 12 Locations to Visit in Europe!</h6>
            </div>
        </div>


    </div>
</div>
<br />
<br />

<div class="container" style="margin-top: 50px">
    <div class="jumbotron">

        <div><h3 style="text-align:center">Top European Locations</h3></div>
        <hr />
        <div class="row">
            <div class="col-4 text-center">
                <h6 style=" margin:0;padding:0;">#1: Paris - France</h6>
                <img class="mx-auto d-block" src="@Url.Content("~/Content/Images/TopEurope/paris.png ")" style="width:320px; height:230px;" />
                <h6 style=" margin:0;padding:0;">Location Fun Fact: </h6><p style=" margin:0;padding:0;">There are 6,100 rues (or streets) in Paris; the shortest one being just 5.75 meters long</p>
                <h6 style=" margin:0;padding:0;">Avg Searched Hotel Star Rating: </h6><p style=" margin:0;padding:0;">@ViewBag.hotelList[0]</p>
                <h6 style=" margin:0;padding:0;">Avg Food Cost Per Day/Per Person: </h6><p style=" margin:0;padding:0;">$31.28</p>
            </div>

            <div class="col-4 text-center">
                <h6 style=" margin:0;padding:0;">#2: Florence - Italy</h6>
                <img class="mx-auto d-block" src="@Url.Content("~/Content/Images/TopEurope/florence.png  ")" style="width:320px; height:230px;" />
                <h6 style=" margin:0;padding:0;">Location Fun Fact: </h6><p style=" margin:0;padding:0;">Nearly a third of the world’s art treasures reside in Florence</p>
                <h6 style=" margin:0;padding:0;">Avg Searched Hotel Star Rating: </h6><p style=" margin:0;padding:0;">@ViewBag.hotelList[1]</p>
                <h6 style=" margin:0;padding:0;">Avg Food Cost Per Day/Per Person: </h6><p style=" margin:0;padding:0;">$26.81</p>
            </div>

            <div class="col-4 text-center">
                <h6 style=" margin:0;padding:0;">#3: Amsterdam - Netherlands</h6>
                <img class="mx-auto d-block" src="@Url.Content("~/Content/Images/TopEurope/amsterdam.png ")" style="width:320px; height:230px;" />
                <h6 style=" margin:0;padding:0;">Location Fun Fact: </h6><p style=" margin:0;padding:0;">Between 12,000 and 15,000 bicycles are pulled out of Amsterdam’s canals each year</p>
                <h6 style=" margin:0;padding:0;">Avg Searched Hotel Star Rating: </h6><p style=" margin:0;padding:0;">@ViewBag.hotelList[2]</p>
                <h6 style=" margin:0;padding:0;">Avg Food Cost Per Day/Per Person: </h6><p style=" margin:0;padding:0;">$34.63</p>
            </div>
            <div class="col-12"><hr /></div>
            <div class="col-4 text-center">
                <h6 style=" margin:0;padding:0;">#4: London - United kingdom</h6>
                <img class="mx-auto d-block" src="@Url.Content("~/Content/Images/TopEurope/london.png  ")" style="width:320px; height:230px;" />
                <h6 style=" margin:0;padding:0;">Location Fun Fact: </h6><p style=" margin:0;padding:0;">To get a london taxi license you have to prove that you know every street/landmark which takes 2-4 years to memorize</p>
                <h6 style=" margin:0;padding:0;">Avg Searched Hotel Star Rating: </h6><p style=" margin:0;padding:0;">@ViewBag.hotelList[3]</p>
                <h6 style=" margin:0;padding:0;">Avg Food Cost Per Day/Per Person: </h6><p style=" margin:0;padding:0;">$36.50</p>
            </div>

            <div class="col-4 text-center">
                <h6 style=" margin:0;padding:0;">#5: Barcelona - Spain</h6>
                <img class="mx-auto d-block" src="@Url.Content("~/Content/Images/TopEurope/barcelona.png ")" style="width:320px; height:230px;" />
                <h6 style=" margin:0;padding:0;">Location Fun Fact: </h6><p style=" margin:0;padding:0;">In Barcelona, they control the pigeon population by mixing birth control chemicals with the birdseed</p>
                <h6 style=" margin:0;padding:0;">Avg Searched Hotel Star Rating: </h6><p style=" margin:0;padding:0;">@ViewBag.hotelList[4]</p>
                <h6 style=" margin:0;padding:0;">Avg Food Cost Per Day/Per Person: </h6><p style=" margin:0;padding:0;">$25.69</p>
            </div>

            <div class="col-4 text-center">
                <h6 style=" margin:0;padding:0;">#6: Rome - Italy</h6>
                <img class="mx-auto d-block" src="@Url.Content("~/Content/Images/TopEurope/rome.png  ")" style="width:320px; height:230px;" />
                <h6 style=" margin:0;padding:0;">Location Fun Fact: </h6><p style=" margin:0;padding:0;">Rome has a sovereign state located entirely in its city limits, the Vatican City, which is also the world’s smallest state</p>
                <h6 style=" margin:0;padding:0;">Avg Searched Hotel Star Rating: </h6><p style=" margin:0;padding:0;">@ViewBag.hotelList[5]</p>
                <h6 style=" margin:0;padding:0;">Avg Food Cost Per Day/Per Person: </h6><p style=" margin:0;padding:0;">$41.33</p>
            </div>
            <div class="col-12"><hr /></div>
            <div class="col-4 text-center">
                <h6 style=" margin:0;padding:0;">#7: Reykjavik - Iceland</h6>
                <img class="mx-auto d-block" src="@Url.Content("~/Content/Images/TopEurope/reykjavik.png  ")" style="width:320px; height:230px;" />
                <h6 style=" margin:0;padding:0;">Location Fun Fact: </h6><p style=" margin:0;padding:0;">Reykjavik gets as little as four hours of sunlight in the winter and as much as 21 hours of daylight in the summer</p>
                <h6 style=" margin:0;padding:0;">Avg Searched Hotel Star Rating: </h6><p style=" margin:0;padding:0;">@ViewBag.hotelList[6]</p>
                <h6 style=" margin:0;padding:0;">Avg Food Cost Per Day/Per Person: </h6><p style=" margin:0;padding:0;">$27.42</p>
            </div>

            <div class="col-4 text-center">
                <h6 style=" margin:0;padding:0;">#8 Edinburgh - Scotland</h6>
                <img class="mx-auto d-block" src="@Url.Content("~/Content/Images/TopEurope/edinburgh.png  ")" style="width:320px; height:230px;" />
                <h6 style=" margin:0;padding:0;">Location Fun Fact: </h6><p style=" margin:0;padding:0;">Edinburgh castle is built on an extinct volcano. The last time the volcano erupted was 350 million years ago</p>
                <h6 style=" margin:0;padding:0;">Avg Searched Hotel Star Rating: </h6><p style=" margin:0;padding:0;">@ViewBag.hotelList[7]</p>
                <h6 style=" margin:0;padding:0;">Avg Food Cost Per Day/Per Person: </h6><p style=" margin:0;padding:0;">$32.59</p>
            </div>

            <div class="col-4 text-center">
                <h6 style=" margin:0;padding:0;">#9  Prague - Czech Republic</h6>
                <img class="mx-auto d-block" src="@Url.Content("~/Content/Images/TopEurope/prague.png  ")" style="width:320px; height:230px;" />
                <h6 style=" margin:0;padding:0;">Location Fun Fact: </h6><p style=" margin:0;padding:0;">
                    It was in prague that the general asembly of Internatinal Astronomical Union meet and redefined Pluto as a dwarf planet in 2006
                </p>
                <h6 style=" margin:0;padding:0;">Avg Searched Hotel Star Rating: </h6><p style=" margin:0;padding:0;">@ViewBag.hotelList[8]</p>
                <h6 style=" margin:0;padding:0;">Avg Food Cost Per Day/Per Person: </h6><p style=" margin:0;padding:0;">$21.00</p>
            </div>
            <div class="col-12"><hr /></div>
            <div class="col-4 text-center">
                <h6 style=" margin:0;padding:0;">#10 Galway - Ireland</h6>
                <img class="mx-auto d-block" src="@Url.Content("~/Content/Images/TopEurope/galway.png  ")" style="width:320px; height:230px;" />
                <h6 style=" margin:0;padding:0;">Location Fun Fact: </h6><p style=" margin:0;padding:0;">Galway is famous for being the festival capital of Ireland, hosting on average 122 festivals and events per year</p>
                <h6 style=" margin:0;padding:0;">Avg Searched Hotel Star Rating: </h6><p style=" margin:0;padding:0;">@ViewBag.hotelList[9]</p>
                <h6 style=" margin:0;padding:0;">Avg Food Cost Per Day/Per Person: </h6><p style=" margin:0;padding:0;">$24.57</p>
            </div>

            <div class="col-4 text-center">
                <h6 style=" margin:0;padding:0;">#11 Nice - France</h6>
                <img class="mx-auto d-block" src="@Url.Content("~/Content/Images/TopEurope/nice.png  ")" style="width:320px; height:230px;" />
                <h6 style=" margin:0;padding:0;">Location Fun Fact: </h6><p style=" margin:0;padding:0;">In Nice, Italian is spoken all around the city, taught in schools alongside English, and also offers a large selection of Italian dishes</p>
                <h6 style=" margin:0;padding:0;">Avg Searched Hotel Star Rating: </h6><p style=" margin:0;padding:0;">@ViewBag.hotelList[10]</p>
                <h6 style=" margin:0;padding:0;">Avg Food Cost Per Day/Per Person: </h6><p style=" margin:0;padding:0;">$43.56</p>
            </div>

            <div class="col-4 text-center">
                <h6 style=" margin:0;padding:0;">#12 Istanbul - Turkey</h6>
                <img class="mx-auto d-block" src="@Url.Content("~/Content/Images/TopEurope/istanbul.png  ")" style="width:320px; height:230px;" />
                <h6 style=" margin:0;padding:0;">Location Fun Fact: </h6><p style=" margin:0;padding:0;">Istanbul is the only city that lies on two continents(Asia and Europe). This fact makes Istanbul to be a centre of trade</p>
                <h6 style=" margin:0;padding:0;">Avg Searched Hotel Star Rating: </h6><p style=" margin:0;padding:0;">@ViewBag.hotelList[11]</p>
                <h6 style=" margin:0;padding:0;">Avg Food Cost Per Day/Per Person: </h6><p style=" margin:0;padding:0;">$5.89</p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm"></div>
            <div class="col-sm">
                @if (Request.IsAuthenticated)
                {
                    var user = User.Identity;
                    ApplicationDbContext context = new ApplicationDbContext();
                    var UserManager = new UserManager<ApplicationUser>
                        (new UserStore<ApplicationUser>
                           (context));
                    var roles = UserManager.GetRoles(user.GetUserId());
                    if (!(roles.Count == 0))
                    {
                        if (roles[0].ToString() == "Admin")
                        {
                            <br />
                            <br />
                            <input class="btn btn-default mx-auto d-block" type="button" value="Show Top Searched Locations" onclick="location.href='@Url.Action("Display", "TopLocations")'" />
                        }
                    }
                }
            </div>
            <div class="col-sm"></div>
        </div>
    </div>
</div>