ReadyGOTravel/readygotravel/readygotravel/Models/Result.cs
namespace readygotravel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Result
    {
        public int ResultID { get; set; }

        public int SearchID { get; set; }

        public decimal AvgHotelStar { get; set; }

        [Column(TypeName = "money")]
        public decimal? AvgFlightAmount { get; set; }

        [Column(TypeName = "money")]
        public decimal? AvgHotelAmount { get; set; }

        [Column(TypeName = "money")]
        public decimal AvgFoodCost { get; set; }

        public virtual Search Search { get; set; }
    }
}

ReadyGOTravel/readygotravel/readygotravel/Models/Search.cs
namespace readygotravel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Search
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Search()
        {
            Results = new HashSet<Result>();
        }

        public int SearchID { get; set; }

        public int UserID { get; set; }

        public DateTime StartDate { get; set; }

        public DateTime EndDate { get; set; }

        public int NumTravelers { get; set; }

        [Column(TypeName = "money"), Required(ErrorMessage = "Please enter only a positive value.")]
        public decimal MaxAmount { get; set; }

        public int? HotelStarValue { get; set; }

        [StringLength(2)]
        public string FlightType { get; set; }

        public int? StartAirport { get; set; }

        public int EndAirport { get; set; }

        public virtual Airport Airport { get; set; }

        public virtual Airport Airport1 { get; set; }

        public virtual Person Person { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Results { get; set; }
    }
}

ReadyGOTravel/readygotravel/readygotravel/Controllers/SearchesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Xml;
using System.Web.Mvc;
using Newtonsoft.Json;
using readygotravel.Models;
using readygotravel.Models.ViewModels;
using Microsoft.AspNet.Identity;
using readygotravel.Abstract;
using System.Web.Script.Serialization;

namespace readygotravel.Controllers
{

    public class SearchesController : Controller
    {
        //The fields for the controller. (db = Database, userDB = ASP.NET User Database, repo = Repository)
        private DBContext db = new DBContext();
        private ApplicationDbContext userDB = new ApplicationDbContext();
        private ITravelRepo repo;

        /// <summary>
        /// The constructor for the SearchesController so testing won't be such a pain in the butt.
        /// </summary>
        /// <param name="travelRepo">The repository, mostly to make testing easier</param>
        public SearchesController(ITravelRepo travelRepo)
        {
            repo = travelRepo;
        }

        /// <summary>
        /// The result page. This method does all the 
        /// </summary>
        /// <param name="id">The ID of the Result object created in the Search View</param>
        /// <param name="left">The amount of money left afterr the flight/hotel costs are removed</param>
        /// <returns>The Result View</returns>
        public ActionResult Result(int? id, decimal? left)
        {
            if (id == null)
            {
                return RedirectToAction("Create");
            }
            if (left == null)
            {
                return RedirectToAction("Create");
            }

            Result result = db.Results.Find(id);

            //Check if a logged in user made the search that has this result. Note: UserID of -1 means it has no user.
            if(result.Search.UserID != -1)
            {
                //Check if user is logged in.
                if (Request.IsAuthenticated)
                {
                    //Get logged in users id.
                    string id2 = User.Identity.GetUserId();

                    //Get peopleID from UserId.
                    int peopleID = db.People.Where(n => n.UserID.Equals(id2)).Select(n => n.PersonID).First();

                    //Note: a UserID by a Search is associated with a PersonID by a Person.
                    //Check if the Search associtate with this Result is relate to the current logged in user.
                    if (result.Search.UserID != peopleID)
                        return RedirectToAction("Create");
                }
                else
                    return RedirectToAction("Create");
            }

            //Make check to see if Adding favorites is an option. Check: if the user is associated with the end state that was searched (in UserState table).
            if (Request.IsAuthenticated)
            {
                //Get logged in users id.
                string id2 = User.Identity.GetUserId();

                //Get peopleID from UserId.
                int peopleID = db.People.Where(n => n.UserID.Equals(id2)).Select(n => n.PersonID).First();//Get logged in users id.

                //Check if user and state is column in UserState table.
                ViewBag.HasFavorite = new FavoritesController(repo).FavoriteOfUserCheck(peopleID, result.Search.Airport1.Location.LocationID);

            }

            ViewBag.Remaining = left;
            if (result.AvgFlightAmount == null)
            {
                ViewBag.Total = result.AvgHotelAmount + result.AvgFoodCost;
            }
            else if (result.AvgHotelAmount == null)
            {
                ViewBag.Total = result.AvgFlightAmount + result.AvgFoodCost;
            }
            else
            {
                ViewBag.Total = result.AvgFlightAmount + result.AvgHotelAmount + result.AvgFoodCost;
            }

            //Makes sure that the average flight amount is not set to 0 or -1 as this would indicate errors
            if (result.AvgFlightAmount != (decimal)0.00 && result.AvgFlightAmount != (decimal)-1.00)
            {
                if (result.AvgFlightAmount == null)
                {
                    if (result.AvgHotelAmount == (decimal)0.00)
                    {
                        ViewBag.Result = 5;
                        ViewBag.Message = "We're sorry.";
                        ViewBag.Message2 = "There were no hotels given your specific parameters.";
                    }
                    //Compare dollar amount available and update the ViewBag results accordingly. 
                    else if (left >= 0)
                    {
                        ViewBag.Result = 0;
                        ViewBag.Message = "You can stay there for: ";
                        ViewBag.Message2 = "And you have this much remaining: ";
                    }
                    else if (left >= -500)
                    {
                        ViewBag.Result = 1;
                        ViewBag.Message = "You can almost stay if you had amount this much more: ";
                    }
                    else
                    {
                        ViewBag.Result = 2;
                        ViewBag.Message = "You are too broke and can't stay on that budget, you would need this much more: ";
                    }
                }
                else
                {
                    //Compare dollar amount available and update the ViewBag results accordingly. 
                    if (left >= 0)
                    {
                        ViewBag.Result = 0;
                        ViewBag.Message = "You can travel there for: ";
                        ViewBag.Message2 = "And you have this much remaining: ";
                    }
                    else if (left >= -500)
                    {
                        ViewBag.Result = 1;
                        ViewBag.Message = "You can almost go if you had amount this much more: ";
                    }
                    else
                    {
                        ViewBag.Result = 2;
                        ViewBag.Message = "You are too broke and can't go on that budget, you would need this much more: ";
                    }
                }


                //Check if the decimal value is 0, if so skip this.
                decimal num = RoundToFourths(result.AvgHotelStar);
                //Get the whole number of the rounded number
                decimal integral = Math.Truncate(num);
                //Get the decimal value of the rounded number
                decimal @decimal = num - integral;

                //Set the whole number and decimal to the View.
                ViewBag.Stars = integral;
                ViewBag.Decimal = @decimal;
            }
            else if (result.AvgFlightAmount == -1)
            {
                ViewBag.Result = 3;
                ViewBag.Message = "Oops your ending location was the same as your starting location!";
                ViewBag.Message2 = "Please update your search options and try again.";
            }
            else
            {
                ViewBag.Result = 4;
                ViewBag.Message = "No flights were available that matched your search criteria.";
                ViewBag.Message2 = "Please update your search options and try again.";
            }

            ViewBag.NumDays = (result.Search.EndDate - result.Search.StartDate).Days;

            decimal[] currencies = GetCurrencyExchanges(result);
            ViewBag.Exchange = currencies[0];
            ViewBag.ExchangeStart = currencies[1];
            if (result.Search.Airport != null)
            {
                ViewBag.CurrencyStart = result.Search.Airport.Location.Country.Currency.CurrencyName;
            }
            ViewBag.Symbol = result.Search.Airport1.Location.Country.Currency.CurrencySymbol;
            ViewBag.Currency = result.Search.Airport1.Location.Country.Currency.CurrencyName;

            //Present information to user
            return View(result);
        }

        /// <summary>
        /// Calls the currency API to get the current currency exchange.
        /// </summary>
        /// <param name="result">The result we want the exchanges for</param>
        /// <returns>an array with the currency exchanges needed.</returns>
        public decimal[] GetCurrencyExchanges(Result result)
        {
            //Get the currency of the ending country
            Currency endCurrency = result.Search.Airport1.Location.Country.Currency;

            //Get the API Key from the AppSecrets File.
            string currencyKey = System.Web.Configuration.WebConfigurationManager.AppSettings["currencyKey"];

            decimal[] currencyExchanges = new decimal[2];
            string currencyURL = "";
            string startKey = "";
            string endKey = "";

            if (result.Search.Airport == null)
            {

                if (endCurrency.CurrencyCode == "USD")
                {
                    currencyExchanges[0] = 1;
                    currencyExchanges[1] = 1;
                    return currencyExchanges;
                }
                else
                {
                    //Construct the Url for the currency API
                    currencyURL = "https://api.currconv.com/api/v7/convert?q=" + "USD" + "_" + endCurrency.CurrencyCode + "&compact=ultra&apiKey=" + currencyKey;
                    startKey = "USD" + "_" + endCurrency.CurrencyCode;
                    //Get the response string from the site so I can start accessing it.
                    string responseString = GetResponseString(currencyURL);

                    //The results.
                    if(responseString != null)
                    { 
                        var results = new JavaScriptSerializer().Deserialize<Dictionary<string, decimal>>(responseString);

ReadyGOTravel/readygotravel/readygotravel/Views/Searches/Create.cshtml
@model readygotravel.Models.ViewModels.SearchDashBoardVM

@{
    ViewBag.Title = "Find a flight and hotel that fits in your budget!";
}

<div class="container">
    <div class="jumbotron">
        <div id="search-portion">
            <h2>Enter your flight and hotel details here!</h2>
            <br />
            <div class="btn-group">
                @Html.ActionLink("Flights/Hotels", "Create", "Searches", null, new { @class = "btn btn-default disabled" })
                @Html.ActionLink("Flights Only", "FlightsOnly", "Searches", null, new { @class = "btn btn-default" })
                @Html.ActionLink("Hotels Only", "HotelsOnly", "Searches", null, new { @class = "btn btn-default" })
            </div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <h4>Travel Dates:</h4>
            <div class="row">

                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-lg-12" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control", placeholder = "mm/dd/yyyy", id = "from" } })
                            @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="form-group">
                        @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-lg-12" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control", placeholder = "mm/dd/yyyy", id = "to" } })
                            @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <hr />
            <section class="departing">
                <h4>Departing From:</h4>
                <div class="row">
                    <!--The Start City/State will Dynamically change depending on the variables using the file Traveling.js-->
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-lg-12">Departing Continent</label>
                            <div class="col-md-10">
                                @Html.DropDownList("StartContinent", new SelectList(ViewBag.Continents, "StartContinent"), htmlAttributes: new { @class = "form-control" })
                                <span class="field-validation-valid text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-lg-12">Departing From</label>
                            <div class="col-md-10">
                                @Html.DropDownList("StartCountry", new SelectList(ViewBag.Countries, "StartCountry"), htmlAttributes: new { @class = "form-control" })
                                <span class="field-validation-valid text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="form-group">
                            <label id="StartLabel" class="control-label col-lg-12">Departing Location</label>
                            <div class="col-md-10">
                                @Html.DropDownList("StartCity", new SelectList(ViewBag.Cities, "StartCity"), htmlAttributes: new { @class = "form-control" })
                                <div class="text-danger">@ViewBag.ErrorMessage</div>
                                <span class="field-validation-valid text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <!--The Start Airport will Go Here using the JavaScript file Traveling.js-->
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-lg-12">Departing Airport </label>
                            <div class="col-md-10">
                                <select class="form-control" name="StartAir" id="StartAirport">
                                    @foreach (var airport in ViewBag.Airports)
                                    {
                                        <option value=@airport.AirportID>@airport.AirportCode</option>
                                    }
                                </select>
                            </div>
                            <span class="field-validation-valid text-danger"></span>
                        </div>
                    </div>
                </div>
            </section>
            <hr />
            <section class="arriving">
                <h4>Arriving At:</h4>
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-lg-12">Arriving Continent</label>
                            <div class="col-md-10">
                                @Html.DropDownList("EndContinent", new SelectList(ViewBag.Continents, "EndContinent"), htmlAttributes: new { @class = "form-control" })
                                <span class="field-validation-valid text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-lg-12">Arriving To</label>
                            <div class="col-md-10">
                                @Html.DropDownList("EndCountry", new SelectList(ViewBag.Countries, "EndCountry"), htmlAttributes: new { @class = "form-control" })
                                <span class="field-validation-valid text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <!--The End City/State will Dynamically change depending on the variables using the file Traveling.js-->
                    <div class="col-md-3">
                        <div class="form-group">
                            <label id="EndLabel" class="control-label col-lg-12">Arriving Location</label>
                            <div class="col-md-10">
                                @Html.DropDownList("EndCity", new SelectList(ViewBag.EndCities, "EndCity"), htmlAttributes: new { @class = "form-control" })
                                <div class="text-danger">@ViewBag.ErrorMessage</div>
                                <span class="field-validation-valid text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <!--The End Airport will dynamically change depending on the variables using Traveling.js-->
                    <div class="col-md-3">
                        <div class="form-group">
                            <label class="control-label col-lg-12">Arriving Airport </label>
                            <div class="col-md-10">                                  
                                <select class="form-control" name="EndAir" id="EndAirport">
                                    @foreach (var airport in ViewBag.EndAirports)
                                     {
                                        <option value=@airport.AirportID>@airport.AirportCode</option>
                                     }
                                 </select>                                 
                            </div>
                            <span class="field-validation-valid text-danger"></span>
                        </div>
                    </div>
                </div>
            </section>
            <hr />
            <section class="travel-detials">
                <h4>Travel Details:</h4>
                <div class="row">
                    <div class="col-md-3">
                        <div class="form-group">
                            @Html.LabelFor(model => model.MaxAmount, htmlAttributes: new { @class = "control-label col-lg-12" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.MaxAmount, new { htmlAttributes = new { @class = "form-control", @min = "1", placeholder = "00.00" } })
                                @Html.ValidationMessageFor(model => model.MaxAmount, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            @Html.LabelFor(model => model.NumTravelers, htmlAttributes: new { @class = "control-label" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.NumTravelers, Enumerable.Range(1, 9).Select(i => new SelectListItem { Text = i.ToString(), Value = i.ToString() }))
                                @Html.ValidationMessageFor(model => model.NumTravelers, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            @Html.LabelFor(model => model.FlightType, htmlAttributes: new { @class = "control-label col-lg-12" })
                            <div class="col-md-10">
                                @Html.DropDownList("FlightType", new SelectList(ViewBag.Flight, "FlightType"), htmlAttributes: new { @class = "form - control" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            @Html.LabelFor(model => model.HotelStarValue, htmlAttributes: new { @class = "control-label col-lg-12" })
                            <div class="col-md-10">
                                @Html.DropDownList("HotelStarValue", new SelectList(ViewBag.Stars, "HotelStarValue"), htmlAttributes: new { @class = "form - control" })
                            </div>
                            <span class="field-validation-valid text-danger"></span>
                        </div>
                    </div>
                </div>
            </section>
            <hr />
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Search" class="btn btn-default" onclick="displayLoading()" />
                        </div>
                    </div>
                </div>
            </div>
            <div>
                <h6>@Html.ActionLink("Back to Home", "Index", "Home")</h6>
            </div>
        </div>
            }
        </div>
    </div>
</div>



@section Scripts {
    <!--The Script for Getting the Cities and Airports to Dynamically Change.-->
    <script type="text/javascript" src="~/Scripts/Traveling.js"></script>

    <!--The Script for the "DatePickers"-->
    <script type="text/javascript">
        $(function () {
            var dateFormat = "mm/dd/yy",
                from = $("#from")
                    .datepicker({
                        minDate: "+1",
                    })
                    .on("change", function () {
                        to.datepicker("option", "minDate", getDate(this));
                    }),
                to = $("#to").datepicker({
                    minDate: "+1",
                })
                    .on("change", function () {
                        from.datepicker("option", "maxDate", getDate(this));
                    });
            function getDate(element) {
                var date;
                try {
                    date = $.datepicker.parseDate(dateFormat, element.value);
                } catch (error) {
                    date = null;
                }
                return date;
            }
        });
    </script>

    <!--Loading indicator part.-->
    <script>
        //Adds loading indicater and clear content as well.
        function displayLoading() {
            //Clear content on page.
            $("#search-portion").attr("style", "display:none");

            //Add main div holding everything.
            var holder = $('<div>', { align: 'center' });

            //Add text part.
            var textPart = $('<h2>').text("Please wait while we process your data. This may take a minute.");
            holder.append(textPart);

            //Making loading indicator.
            var loadingPart = $('<div>', { class: 'loadingdiv' });
            loadingPart.append($('<div>', { class: 'alignBar' }));
            for (i = 0; i < 5; i++)
                loadingPart.append($('<span>'));
            holder.append(loadingPart);

            //add loading indicator to page.
            $(".jumbotron").append(holder);
        }
    </script>
}

ReadyGOTravel/readygotravel/readygotravel/Views/Searches/Delete.cshtml
@model readygotravel.Models.Search

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Search</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Person.UserID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person.UserID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumTravelers)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumTravelers)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MaxAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxAmount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartAirport)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartAirport)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndAirport)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndAirport)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ReadyGOTravel/readygotravel/readygotravel/Views/Searches/DeleteAll.cshtml
@{
    ViewBag.Title = "DeleteAll";
}

<div class="container">
    <div class="jumbotron">
        <h2>Clear Search History</h2>
        <hr />
        <h4>Search History Count: @ViewBag.searchesCount</h4>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">

                @*check if has have any searches to display and then display message depending on that.*@
                @if (ViewBag.searchesCount >= 1)
                {
                    <h4>Are you sure you want to clear your search history?</h4>


                    @*Button to confirm deletion of search history*@
                    <input type="submit" value="yes" class="btn btn-default" />

                    @*Button to return to Search History page*@
                    @Html.ActionLink("No", "UserSearches", "Searches", null, new { @class = "btn navbar-btn" })

                }
                else
                {
                    <h4>No searches in your search history? Have a budget and a destination you want to go to?</h4>
                    <h4> Try making some searches @Html.ActionLink("here.", "Create", "Search")</h4>
                    @*Button to return to Search History page*@
                    @Html.ActionLink("Back", "UserSearches", "Searches", null, new { @class = "btn navbar-btn" })
                }
            </div>
        }

    </div>
</div>

ReadyGOTravel/readygotravel/readygotravel/Views/Searches/UserSearches.cshtml
@model IEnumerable<readygotravel.Models.Search>
@{
    ViewBag.Title = "Search History";
}

<div class="container">
    <div class="jumbotron">
        <h2 class="text-center">Search History</h2>
        <h5 class="text-center">View past searches and results here!</h5>
        @if (ViewBag.TotalSearches != 0)
        {
            <div class="text-right">
                <!--button to go to clear search history page-->
                @Html.ActionLink("Clear Search History", "DeleteAll", "Searches", null, new { @class = "btn navbar-btn" })

            </div>
        }
        <hr />
        <table class="table">
            <tr>
                <th>
                    Start Date
                </th>
                <th>
                    End Date
                </th>
                <th>
                    # Travelers
                </th>
                <th>
                    Max Amount
                </th>
                <th>
                    Start Location
                </th>
                <th>
                    End Location
                </th>
                <th>
                    Hotel Star Value
                </th>
                <th></th>
            </tr>

        </table>
        <!--Used this to reference how many search items are on display-->
        <input type="hidden" value=0 id="TotalElements">
        <input type="hidden" value=@ViewBag.TotalSearches id="TotalSearches">

        <!--"load more" button-->
        <div class="text-center">
            @Html.TextBox("submited", "Load More", htmlAttributes: new { @class = "btn", type = "submit", style = "max-width:250px; display:none" })
        </div>

        <hr />
        @Html.ActionLink("Back to Profile", "Details", "People", null, new { @class = "btn navbar-btn" })
    </div>
</div>

    @section PageScripts{
        <script type="text/javascript" src="~/Scripts/AddMoreSearches.js"></script>
        <script>addElements()</script>

    }